package com.mkwang.backend.modules.request.entity;

import lombok.*;

import java.io.Serializable;

/**
 * Composite Primary Key for RequestAttachment entity.
 * Represents the many-to-many relationship between Request and FileStorage.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
public class RequestAttachmentId implements Serializable {

    private Long request;
    private Long file;

    // equals() and hashCode() are auto-generated by @EqualsAndHashCode
}


