-- =============================================================================
-- V10: Add advance_balances table for ADVANCE debt tracking (Hướng 2)
--      + advance_balance_id FK on requests (for REIMBURSE linkage)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. advance_balances — one record per approved ADVANCE payout
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS advance_balances
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    advance_request_id  BIGINT                                  NOT NULL,

    -- Amounts (all non-negative; remaining = original - reimbursed - returned)
    original_amount     DECIMAL(19, 2)                          NOT NULL,
    reimbursed_amount   DECIMAL(19, 2) DEFAULT 0                NOT NULL,
    returned_amount     DECIMAL(19, 2) DEFAULT 0                NOT NULL,
    remaining_amount    DECIMAL(19, 2)                          NOT NULL,

    status              VARCHAR(20)                             NOT NULL, -- OUTSTANDING | PARTIALLY_SETTLED | SETTLED
    settled_at          TIMESTAMP WITHOUT TIME ZONE,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_advance_balances PRIMARY KEY (id),
    CONSTRAINT uc_advance_balance_request UNIQUE (advance_request_id),

    -- remaining must always be >= 0
    CONSTRAINT chk_advance_remaining_non_negative CHECK (remaining_amount >= 0)
);

-- Accountant dashboard: "show all outstanding advances per user"
CREATE INDEX IF NOT EXISTS idx_advance_balance_user_status ON advance_balances (user_id, status);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_advance_balance_user'
    ) THEN
        ALTER TABLE advance_balances
            ADD CONSTRAINT fk_advance_balance_user
            FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_advance_balance_request'
    ) THEN
        ALTER TABLE advance_balances
            ADD CONSTRAINT fk_advance_balance_request
            FOREIGN KEY (advance_request_id) REFERENCES requests (id);
    END IF;
END$$;

-- -----------------------------------------------------------------------------
-- 2. requests: add advance_balance_id (REIMBURSE → AdvanceBalance linkage)
-- -----------------------------------------------------------------------------
ALTER TABLE requests ADD COLUMN IF NOT EXISTS advance_balance_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_request_advance_balance'
    ) THEN
        ALTER TABLE requests
            ADD CONSTRAINT fk_request_advance_balance
            FOREIGN KEY (advance_balance_id) REFERENCES advance_balances (id);
    END IF;
END$$;
