-- =============================================================================
-- V13: Add withdrawal_requests table + seq_withdraw_code sequence
-- =============================================================================

-- Sequence cho WithdrawCode (WD-2026-000001)
CREATE SEQUENCE IF NOT EXISTS seq_withdraw_code START WITH 1 INCREMENT BY 1;

-- withdrawal_requests table
CREATE TABLE IF NOT EXISTS withdrawal_requests
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    withdraw_code        VARCHAR(30)    NOT NULL,
    user_id              BIGINT         NOT NULL,
    amount               DECIMAL(19, 2) NOT NULL,

    -- Snapshot bank info from UserProfile at submission time
    credit_account       VARCHAR(30)    NOT NULL,
    credit_account_name  VARCHAR(100)   NOT NULL,
    credit_bank_code     VARCHAR(20)    NOT NULL,
    credit_bank_name     VARCHAR(100)   NOT NULL,

    user_note            VARCHAR(500),
    status               VARCHAR(20)    NOT NULL,

    -- Filled after MockBank response
    bank_transaction_id  VARCHAR(50),
    accountant_note      VARCHAR(500),
    executed_by          BIGINT,
    executed_at          TIMESTAMP WITHOUT TIME ZONE,
    transaction_id       BIGINT,
    failure_reason       VARCHAR(500),

    -- BaseEntity audit fields
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    created_by           BIGINT,
    updated_by           BIGINT,

    CONSTRAINT pk_withdrawal_requests PRIMARY KEY (id),
    CONSTRAINT uk_wr_withdraw_code UNIQUE (withdraw_code),
    CONSTRAINT wr_status_check CHECK (status IN (
        'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REJECTED', 'CANCELLED'
    ))
);

CREATE INDEX IF NOT EXISTS idx_wr_user_id   ON withdrawal_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_wr_status    ON withdrawal_requests (status);
CREATE INDEX IF NOT EXISTS idx_wr_created   ON withdrawal_requests (created_at);
