-- =============================================================================
-- V16: Add deposit_logs table + seq_deposit_code sequence
-- =============================================================================

CREATE SEQUENCE IF NOT EXISTS seq_deposit_code START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS deposit_logs
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_code        VARCHAR(30)    NOT NULL,
    user_id             BIGINT         NOT NULL,
    amount              DECIMAL(19, 2) NOT NULL,
    status              VARCHAR(20)    NOT NULL,
    vnp_transaction_no  VARCHAR(50),
    vnp_response_code   VARCHAR(5),
    paid_at             TIMESTAMP WITHOUT TIME ZONE,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          BIGINT,
    updated_by          BIGINT,
    CONSTRAINT pk_deposit_logs    PRIMARY KEY (id),
    CONSTRAINT uk_dl_deposit_code UNIQUE (deposit_code),
    CONSTRAINT dl_status_check    CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_dl_user_id      ON deposit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_dl_deposit_code ON deposit_logs (deposit_code);
CREATE INDEX IF NOT EXISTS idx_dl_status       ON deposit_logs (status);
