-- Accounting journals and explicit advance settlement sources for ledger redesign.

CREATE TABLE IF NOT EXISTS accounting_journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_code VARCHAR(40) NOT NULL UNIQUE,
    event_type VARCHAR(30) NOT NULL,
    posting_date DATE NOT NULL,
    posting_period VARCHAR(7) NOT NULL,
    description TEXT NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id VARCHAR(80) NOT NULL,
    request_id BIGINT,
    advance_balance_id BIGINT,
    employee_id BIGINT,
    employee_name VARCHAR(200),
    project_id BIGINT,
    project_name VARCHAR(200),
    wallet_transaction_id BIGINT,
    total_amount DECIMAL(19,2) NOT NULL CHECK (total_amount > 0),
    CONSTRAINT uc_accounting_journal_event_source UNIQUE (event_type, source_type, source_id)
);

CREATE INDEX IF NOT EXISTS idx_accounting_journal_posting_date ON accounting_journals (posting_date);
CREATE INDEX IF NOT EXISTS idx_accounting_journal_request ON accounting_journals (request_id);
CREATE INDEX IF NOT EXISTS idx_accounting_journal_advance ON accounting_journals (advance_balance_id);
CREATE INDEX IF NOT EXISTS idx_accounting_journal_wallet_txn ON accounting_journals (wallet_transaction_id);

CREATE TABLE IF NOT EXISTS accounting_journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id BIGINT NOT NULL REFERENCES accounting_journals (id) ON DELETE CASCADE,
    line_number INTEGER NOT NULL,
    account_code VARCHAR(40) NOT NULL,
    account_name VARCHAR(150) NOT NULL,
    debit_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
    credit_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
    effect_description VARCHAR(500) NOT NULL,
    advance_balance_id BIGINT,
    request_id BIGINT,
    employee_id BIGINT,
    project_id BIGINT,
    CONSTRAINT uc_accounting_journal_line_number UNIQUE (journal_id, line_number),
    CONSTRAINT chk_accounting_journal_line_one_side CHECK (
        (debit_amount > 0 AND credit_amount = 0) OR
        (credit_amount > 0 AND debit_amount = 0)
    )
);

CREATE INDEX IF NOT EXISTS idx_accounting_journal_line_advance ON accounting_journal_lines (advance_balance_id);

ALTER TABLE requests ADD COLUMN IF NOT EXISTS reserved_amount DECIMAL(19,2) NOT NULL DEFAULT 0;
UPDATE requests
SET reserved_amount = COALESCE(approved_amount, amount)
WHERE status = 'APPROVED_BY_TEAM_LEADER' AND type IN ('ADVANCE', 'EXPENSE')
  AND reserved_amount = 0;

-- Older returned_amount mixed actual cash returns with payroll offsets. Preserve its value,
-- but label it as unclassified so reports do not claim an unsupported source.
ALTER TABLE advance_balances ADD COLUMN IF NOT EXISTS cash_returned_amount DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE advance_balances ADD COLUMN IF NOT EXISTS payroll_offset_amount DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE advance_balances ADD COLUMN IF NOT EXISTS legacy_unclassified_amount DECIMAL(19,2) NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'advance_balances' AND column_name = 'returned_amount'
    ) THEN
        UPDATE advance_balances
        SET legacy_unclassified_amount = COALESCE(returned_amount, 0);
        ALTER TABLE advance_balances DROP COLUMN returned_amount;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_advance_balance_status_remaining
    ON advance_balances (status, remaining_amount);
