CREATE TABLE audit_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id    BIGINT,
    action      VARCHAR(50)                             NOT NULL,
    entity_name VARCHAR(100)                            NOT NULL,
    entity_id   VARCHAR(100)                            NOT NULL,
    old_values  JSONB,
    new_values  JSONB,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by              BIGINT,
    updated_by              BIGINT,
    name                    VARCHAR(255)                            NOT NULL,
    code                    VARCHAR(20)                             NOT NULL,
    manager_id              BIGINT,
    total_project_quota     DECIMAL(19, 2) DEFAULT 0,
    total_available_balance DECIMAL(19, 2) DEFAULT 0,
    version                 BIGINT,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE expense_categories
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    description       TEXT,
    is_system_default BOOLEAN DEFAULT FALSE                   NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        BIGINT,
    updated_by        BIGINT,
    CONSTRAINT pk_expense_categories PRIMARY KEY (id)
);

CREATE TABLE file_storages
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by           BIGINT,
    updated_by           BIGINT,
    file_name            VARCHAR(255)                            NOT NULL,
    cloudinary_public_id VARCHAR(255)                            NOT NULL,
    url                  TEXT                                    NOT NULL,
    file_type            VARCHAR(100),
    size                 BIGINT,
    CONSTRAINT pk_file_storages PRIMARY KEY (id)
);

CREATE TABLE jwt_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(1000)                           NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    token_type  VARCHAR(20)                             NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked     BOOLEAN                                 NOT NULL,
    revoked_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_jwt_tokens PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    user_id    BIGINT                                  NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    message    TEXT,
    type       VARCHAR(30)                             NOT NULL,
    ref_id     BIGINT,
    ref_type   VARCHAR(50),
    is_read    BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE payroll_periods
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  BIGINT,
    updated_by  BIGINT,
    period_code VARCHAR(30)                             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    month       INTEGER                                 NOT NULL,
    year        INTEGER                                 NOT NULL,
    start_date  date,
    end_date    date,
    status      VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_payroll_periods PRIMARY KEY (id)
);

CREATE TABLE payslips
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       BIGINT,
    updated_by       BIGINT,
    payslip_code     VARCHAR(30)                             NOT NULL,
    period_id        BIGINT                                  NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    base_salary      DECIMAL(19, 2)                          NOT NULL,
    bonus            DECIMAL(19, 2),
    allowance        DECIMAL(19, 2),
    deduction        DECIMAL(19, 2),
    advance_deduct   DECIMAL(19, 2) DEFAULT 0,
    final_net_salary DECIMAL(19, 2),
    status           VARCHAR(20)                             NOT NULL,
    payment_date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payslips PRIMARY KEY (id)
);

CREATE TABLE phase_category_budgets
(
    phase_id      BIGINT         NOT NULL,
    category_id   BIGINT         NOT NULL,
    budget_limit  DECIMAL(19, 2) NOT NULL,
    current_spent DECIMAL(19, 2) DEFAULT 0,
    CONSTRAINT pk_phase_category_budgets PRIMARY KEY (phase_id, category_id)
);

CREATE TABLE project_members
(
    project_role VARCHAR(20)                 NOT NULL,
    position     VARCHAR(100),
    joined_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    project_id   BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    CONSTRAINT pk_project_members PRIMARY KEY (project_id, user_id)
);

CREATE TABLE project_phases
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    phase_code    VARCHAR(30)                             NOT NULL,
    project_id    BIGINT                                  NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    budget_limit  DECIMAL(19, 2),
    current_spent DECIMAL(19, 2) DEFAULT 0,
    status        VARCHAR(20)                             NOT NULL,
    start_date    date,
    end_date      date,
    CONSTRAINT pk_project_phases PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       BIGINT,
    updated_by       BIGINT,
    project_code     VARCHAR(30)                             NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    department_id    BIGINT                                  NOT NULL,
    manager_id       BIGINT                                  NOT NULL,
    total_budget     DECIMAL(19, 2),
    available_budget DECIMAL(19, 2) DEFAULT 0,
    total_spent      DECIMAL(19, 2) DEFAULT 0,
    status           VARCHAR(20)                             NOT NULL,
    current_phase_id BIGINT,
    version          BIGINT,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE request_attachments
(
    request_id BIGINT NOT NULL,
    file_id    BIGINT NOT NULL,
    CONSTRAINT pk_request_attachments PRIMARY KEY (request_id, file_id)
);

CREATE TABLE request_histories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id          BIGINT                                  NOT NULL,
    actor_id            BIGINT                                  NOT NULL,
    action              VARCHAR(20)                             NOT NULL,
    status_after_action VARCHAR(25)                             NOT NULL,
    comment             VARCHAR(500),
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_request_histories PRIMARY KEY (id)
);

CREATE TABLE requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      BIGINT,
    updated_by      BIGINT,
    request_code    VARCHAR(30)                             NOT NULL,
    requester_id    BIGINT                                  NOT NULL,
    project_id      BIGINT,
    phase_id        BIGINT,
    category_id     BIGINT,
    type            VARCHAR(20)                             NOT NULL,
    amount          DECIMAL(19, 2)                          NOT NULL,
    approved_amount DECIMAL(19, 2),
    status          VARCHAR(25)                             NOT NULL,
    reject_reason   TEXT,
    description     TEXT,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    role_id    BIGINT      NOT NULL,
    permission VARCHAR(50) NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  BIGINT,
    updated_by  BIGINT,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE system_configs
(
    config_key   VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by   BIGINT,
    updated_by   BIGINT,
    config_value VARCHAR(255) NOT NULL,
    description  TEXT,
    CONSTRAINT pk_system_configs PRIMARY KEY (config_key)
);

CREATE TABLE system_funds
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    total_balance DECIMAL(19, 2)                          NOT NULL,
    bank_account  VARCHAR(30),
    bank_name     VARCHAR(100),
    CONSTRAINT pk_system_funds PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by             BIGINT,
    updated_by             BIGINT,
    transaction_code       VARCHAR(30)                             NOT NULL,
    payment_ref            VARCHAR(100),
    gateway_provider       VARCHAR(20),
    wallet_id              BIGINT                                  NOT NULL,
    amount                 DECIMAL(19, 2)                          NOT NULL,
    balance_after          DECIMAL(19, 2)                          NOT NULL,
    type                   VARCHAR(30)                             NOT NULL,
    status                 VARCHAR(20)                             NOT NULL,
    reference_type         VARCHAR(30),
    reference_id           BIGINT,
    related_transaction_id BIGINT,
    actor_id               BIGINT,
    description            TEXT,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE user_profiles
(
    user_id            BIGINT NOT NULL,
    employee_code      VARCHAR(20),
    job_title          VARCHAR(100),
    phone_number       VARCHAR(15),
    date_of_birth      date,
    citizen_id         VARCHAR(20),
    address            VARCHAR(255),
    avatar_file_id     BIGINT,
    bank_name          VARCHAR(100),
    bank_account_num   VARCHAR(30),
    bank_account_owner VARCHAR(100),
    CONSTRAINT pk_user_profiles PRIMARY KEY (user_id)
);

CREATE TABLE user_security_settings
(
    user_id         BIGINT NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by      BIGINT,
    updated_by      BIGINT,
    transaction_pin VARCHAR(100),
    retry_count     INTEGER,
    locked_until    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_security_settings PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by              BIGINT,
    updated_by              BIGINT,
    email                   VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    full_name               VARCHAR(255),
    is_first_login          BOOLEAN                                 NOT NULL,
    role_id                 BIGINT                                  NOT NULL,
    department_id           BIGINT,
    status                  VARCHAR(20)                             NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    account_non_expired     BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE wallets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      BIGINT,
    updated_by      BIGINT,
    user_id         BIGINT                                  NOT NULL,
    balance         DECIMAL(19, 2) DEFAULT 0                NOT NULL,
    pending_balance DECIMAL(19, 2) DEFAULT 0                NOT NULL,
    debt_balance    DECIMAL(19, 2) DEFAULT 0                NOT NULL,
    version         BIGINT,
    CONSTRAINT pk_wallets PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_code UNIQUE (code);

ALTER TABLE file_storages
    ADD CONSTRAINT uc_file_storages_cloudinary_public UNIQUE (cloudinary_public_id);

ALTER TABLE jwt_tokens
    ADD CONSTRAINT uc_jwt_tokens_token UNIQUE (token);

ALTER TABLE payroll_periods
    ADD CONSTRAINT uc_payroll_periods_period_code UNIQUE (period_code);

ALTER TABLE payslips
    ADD CONSTRAINT uc_payslips_payslip_code UNIQUE (payslip_code);

ALTER TABLE project_phases
    ADD CONSTRAINT uc_project_phases_phase_code UNIQUE (phase_code);

ALTER TABLE projects
    ADD CONSTRAINT uc_projects_current_phase UNIQUE (current_phase_id);

ALTER TABLE projects
    ADD CONSTRAINT uc_projects_project_code UNIQUE (project_code);

ALTER TABLE request_attachments
    ADD CONSTRAINT uc_request_attachments_file UNIQUE (file_id);

ALTER TABLE requests
    ADD CONSTRAINT uc_requests_request_code UNIQUE (request_code);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE transactions
    ADD CONSTRAINT uc_transactions_transaction_code UNIQUE (transaction_code);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_employee_code UNIQUE (employee_code);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_phone_number UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE wallets
    ADD CONSTRAINT uc_wallets_user UNIQUE (user_id);

CREATE INDEX idx_departments_code ON departments (code);

CREATE INDEX idx_payroll_periods_period_code ON payroll_periods (period_code);

CREATE INDEX idx_payslips_payslip_code ON payslips (payslip_code);

CREATE INDEX idx_project_phases_phase_code ON project_phases (phase_code);

CREATE INDEX idx_projects_project_code ON projects (project_code);

CREATE INDEX idx_requests_request_code ON requests (request_code);

CREATE INDEX idx_token ON jwt_tokens (token);

CREATE INDEX idx_token_type ON jwt_tokens (token_type);

CREATE INDEX idx_transactions_transaction_code ON transactions (transaction_code);

CREATE INDEX idx_user_profiles_employee_code ON user_profiles (employee_code);

CREATE INDEX idx_user_profiles_phone_number ON user_profiles (phone_number);

CREATE INDEX idx_user_revoked ON jwt_tokens (user_id, revoked);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES users (id);

ALTER TABLE jwt_tokens
    ADD CONSTRAINT FK_JWT_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payslips
    ADD CONSTRAINT FK_PAYSLIPS_ON_PERIOD FOREIGN KEY (period_id) REFERENCES payroll_periods (id);

ALTER TABLE payslips
    ADD CONSTRAINT FK_PAYSLIPS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_CURRENT_PHASE FOREIGN KEY (current_phase_id) REFERENCES project_phases (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES users (id);

ALTER TABLE project_members
    ADD CONSTRAINT FK_PROJECT_MEMBERS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE project_members
    ADD CONSTRAINT FK_PROJECT_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE project_phases
    ADD CONSTRAINT FK_PROJECT_PHASES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_PHASE FOREIGN KEY (phase_id) REFERENCES project_phases (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id);

ALTER TABLE request_histories
    ADD CONSTRAINT FK_REQUEST_HISTORIES_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

ALTER TABLE request_histories
    ADD CONSTRAINT FK_REQUEST_HISTORIES_ON_REQUEST FOREIGN KEY (request_id) REFERENCES requests (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_RELATED_TRANSACTION FOREIGN KEY (related_transaction_id) REFERENCES transactions (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_WALLET FOREIGN KEY (wallet_id) REFERENCES wallets (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_AVATAR_FILE FOREIGN KEY (avatar_file_id) REFERENCES file_storages (id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_security_settings
    ADD CONSTRAINT FK_USER_SECURITY_SETTINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE wallets
    ADD CONSTRAINT FK_WALLETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE request_attachments
    ADD CONSTRAINT fk_reqatt_on_file_storage FOREIGN KEY (file_id) REFERENCES file_storages (id);

ALTER TABLE request_attachments
    ADD CONSTRAINT fk_reqatt_on_request FOREIGN KEY (request_id) REFERENCES requests (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE expense_categories
    ADD CONSTRAINT uc_expense_categories_name UNIQUE (name);

ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES expense_categories (id);

ALTER TABLE phase_category_budgets
    ADD CONSTRAINT FK_PHASE_CAT_BUDGETS_ON_PHASE FOREIGN KEY (phase_id) REFERENCES project_phases (id);

ALTER TABLE phase_category_budgets
    ADD CONSTRAINT FK_PHASE_CAT_BUDGETS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES expense_categories (id);
