-- =============================================================================
-- V8: Refactor Wallet (unified owner model) + Transaction (remove audit fields)
--     + Add ledger_entries table (double-entry bookkeeping)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. WALLETS: migrate from user-only to unified owner model
-- -----------------------------------------------------------------------------

-- 1a. Add new owner columns (nullable first to allow data migration)
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS owner_type VARCHAR(20);
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS owner_id   BIGINT;

-- 1b. Migrate existing user wallets: user_id → (USER, user_id)
--     Wrapped in DO block so it is skipped safely if user_id column no longer exists
--     (handles the case where V8 was partially applied and then rolled back).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name   = 'wallets'
          AND column_name  = 'user_id'
    ) THEN
        UPDATE wallets
        SET owner_type = 'USER',
            owner_id   = user_id
        WHERE owner_type IS NULL;
    END IF;
END$$;

-- 1c. Now enforce NOT NULL
ALTER TABLE wallets ALTER COLUMN owner_type SET NOT NULL;
ALTER TABLE wallets ALTER COLUMN owner_id   SET NOT NULL;

-- 1d. Drop old columns.
--     CASCADE drops every FK / unique constraint that depends on these columns,
--     regardless of whether the constraint was named by V1 or auto-generated by Hibernate.
ALTER TABLE wallets DROP COLUMN IF EXISTS user_id          CASCADE;
ALTER TABLE wallets DROP COLUMN IF EXISTS pending_balance  CASCADE;
ALTER TABLE wallets DROP COLUMN IF EXISTS debt_balance     CASCADE;

-- 1e. Add locked_balance
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS locked_balance DECIMAL(19, 2) DEFAULT 0 NOT NULL;

-- 1f. Add unique constraint on (owner_type, owner_id)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uk_wallet_owner' AND conrelid = 'wallets'::regclass
    ) THEN
        ALTER TABLE wallets ADD CONSTRAINT uk_wallet_owner UNIQUE (owner_type, owner_id);
    END IF;
END$$;


-- -----------------------------------------------------------------------------
-- 2. DEPARTMENTS: drop version (financial state moves to Wallet)
-- -----------------------------------------------------------------------------
ALTER TABLE departments DROP COLUMN IF EXISTS version;


-- -----------------------------------------------------------------------------
-- 3. PROJECTS: drop version (financial state moves to Wallet)
-- -----------------------------------------------------------------------------
ALTER TABLE projects DROP COLUMN IF EXISTS version;


-- -----------------------------------------------------------------------------
-- 4. TRANSACTIONS: strip down to pure business event record
-- -----------------------------------------------------------------------------

-- 4a. Drop FK-bearing columns with CASCADE.
--     This removes FK_TRANSACTIONS_ON_ACTOR, FK_TRANSACTIONS_ON_RELATED_TRANSACTION,
--     and FK_TRANSACTIONS_ON_WALLET regardless of their actual constraint names.
ALTER TABLE transactions DROP COLUMN IF EXISTS actor_id               CASCADE;
ALTER TABLE transactions DROP COLUMN IF EXISTS related_transaction_id CASCADE;
ALTER TABLE transactions DROP COLUMN IF EXISTS wallet_id              CASCADE;

-- 4b. Drop old plain index (will recreate with better naming)
DROP INDEX IF EXISTS idx_transactions_transaction_code;

-- 4c. Drop remaining audit columns no longer owned by Transaction
ALTER TABLE transactions DROP COLUMN IF EXISTS updated_at;
ALTER TABLE transactions DROP COLUMN IF EXISTS updated_by;
ALTER TABLE transactions DROP COLUMN IF EXISTS created_by;
ALTER TABLE transactions DROP COLUMN IF EXISTS balance_after;

-- 4d. Recreate indexes aligned with new query patterns
CREATE INDEX IF NOT EXISTS idx_txn_code      ON transactions (transaction_code);
CREATE INDEX IF NOT EXISTS idx_txn_reference ON transactions (reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_txn_created   ON transactions (created_at);


-- -----------------------------------------------------------------------------
-- 5. LEDGER_ENTRIES: double-entry accounting lines
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ledger_entries
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id BIGINT                                  NOT NULL,
    wallet_id      BIGINT                                  NOT NULL,
    direction      VARCHAR(10)                             NOT NULL, -- DEBIT | CREDIT
    amount         DECIMAL(19, 2)                          NOT NULL,
    balance_after  DECIMAL(19, 2)                          NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_ledger_entries PRIMARY KEY (id)
);

-- Index for wallet history queries (ORDER BY created_at)
CREATE INDEX IF NOT EXISTS idx_ledger_wallet_created ON ledger_entries (wallet_id, created_at);

-- Index for double-entry integrity checks (find both sides of a transaction)
CREATE INDEX IF NOT EXISTS idx_ledger_transaction ON ledger_entries (transaction_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ledger_on_transaction'
    ) THEN
        ALTER TABLE ledger_entries
            ADD CONSTRAINT FK_LEDGER_ON_TRANSACTION
            FOREIGN KEY (transaction_id) REFERENCES transactions (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ledger_on_wallet'
    ) THEN
        ALTER TABLE ledger_entries
            ADD CONSTRAINT FK_LEDGER_ON_WALLET
            FOREIGN KEY (wallet_id) REFERENCES wallets (id);
    END IF;
END$$;
